---
title: OpenSpool
description: Your filament wants to be free
theme: just-the-docs
url: https://openspool.io
aux_links:
  "Edit this page on Github":
    - https://github.com/spuder/openspool
logo: "images/OpenSpoolLogoMedium1.png"
favicon: "images/favicon.ico"
color_scheme: dark
plugins:
  - jekyll-default-layout
head_scripts:
  # https://github.com/esphome/esp-web-tools/issues/515#issuecomment-2387664391
  # - https://unpkg.com/@improv-wifi/sdk-serial@1.1.0/dist/serial.min.js?module
  - https://unpkg.com/esp-web-tools@8.0.6/dist/web/install-button.js?module
  # - https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js
defaults:
  - scope:
      path: "assets/js"
    values:
      js: true
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: blue
  caution:
    title: Caution
    color: yellow

# footer_content: "Copyright &copy; 2017-2020 Patrick Marsceill. Distributed by an <a href=\"https://github.com/just-the-docs/just-the-docs/tree/main/LICENSE.txt\">MIT license.</a>"

# # Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub."
# gh_edit_repository: "https://github.com/just-the-docs/just-the-docs" # the github URL for your repo
# gh_edit_branch: "main" # the branch that your docs is served from
# # gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
